import JSZip from 'jszip';
import { ProjectState } from '../types';

export async function downloadProjectAsZip(project: ProjectState): Promise<{ fileName: string; fileCount: number }> {
  const zip = new JSZip();

  // Clean slug for the zip file
  const slug = (project.name || 'project')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '') || 'autoloop-project';

  let count = 0;
  const hasReadme = project.files.some(f => f.path.toLowerCase() === 'readme.md');
  const hasPackageJson = project.files.some(f => f.path.toLowerCase() === 'package.json');

  // Add all project code files
  for (const file of project.files) {
    if (file.path && typeof file.content === 'string') {
      // Clean path to prevent leading slashes
      const cleanPath = file.path.replace(/^\/+/, '');
      zip.file(cleanPath, file.content);
      count++;
    }
  }

  // Include README if not already present
  if (!hasReadme) {
    const readmeContent = `# ${project.name || 'Autonomous Project'}

> Generated by AutoLoop Autonomous Dev Agent
> Original Objective: "${project.originalUserPrompt || project.objective}"

## Project Overview
- **Status:** ${project.status}
- **Autonomous Tasks Completed:** ${project.metrics?.completedTasks || 0} / ${project.tasks?.length || 0}
- **Tests Passing:** ${project.metrics?.passingTests || 0} / ${project.testCases?.length || 0}
- **Files Generated:** ${count}
- **Created At:** ${project.createdAt || new Date().toISOString()}

## Local Execution Instructions

### Prerequisites
- Node.js (v18 or higher recommended)
- npm or yarn

### Quick Start
1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Run the application:
   \`\`\`bash
   npm start
   \`\`\`
   or for Vite / dev projects:
   \`\`\`bash
   npm run dev
   \`\`\`

3. Run verification tests:
   \`\`\`bash
   npm test
   \`\`\`
`;
    zip.file('README.md', readmeContent);
    count++;
  }

  // If no package.json exists, add a standard runner package.json
  if (!hasPackageJson) {
    const defaultPackageJson = {
      name: slug,
      version: '1.0.0',
      description: project.objective || project.name,
      type: 'module',
      scripts: {
        start: 'node src/index.js || node server.js || node index.js',
        dev: 'node --watch src/index.js || vite',
        test: 'node --test'
      },
      dependencies: {},
      devDependencies: {}
    };
    zip.file('package.json', JSON.stringify(defaultPackageJson, null, 2));
    count++;
  }

  // Add metadata descriptor
  const metadata = {
    projectName: project.name,
    objective: project.originalUserPrompt || project.objective,
    generatedBy: 'AutoLoop Autonomous Dev Agent',
    exportTimestamp: new Date().toISOString(),
    filesIncluded: count,
    definitionOfDone: project.definitionOfDone.map(d => ({
      label: d.label,
      status: d.status,
      category: d.category
    }))
  };
  zip.file('.autoloop-export.json', JSON.stringify(metadata, null, 2));

  // Generate ZIP blob
  const zipBlob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 }
  });

  const fileName = `${slug}-source.zip`;
  const blobUrl = URL.createObjectURL(zipBlob);

  const anchor = document.createElement('a');
  anchor.href = blobUrl;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);

  setTimeout(() => {
    URL.revokeObjectURL(blobUrl);
  }, 10000);

  return { fileName, fileCount: count };
}
